// Fichier généré par scripts/index-visuels.mjs : ne pas modifier à la main.
export const VISUELS: Record<string, string[]> = {
 "mascottes": [
  "mia",
  "mia-dessine",
  "mia-dort",
  "mia-encourage",
  "mia-explique-droite",
  "mia-explique-gauche",
  "mia-fier",
  "mia-idee",
  "mia-joie",
  "mia-neutre",
  "mia-reflexion",
  "mia-salut",
  "mia-surprise",
  "mia-triste",
  "neo",
  "neo-coup-de-queue",
  "neo-defi",
  "neo-dort",
  "neo-encourage",
  "neo-explique-droite",
  "neo-explique-gauche",
  "neo-fier",
  "neo-joie",
  "neo-loupe",
  "neo-neutre",
  "neo-reflexion",
  "neo-salut",
  "neo-surprise",
  "neo-triste",
  "zero",
  "zero-dort",
  "zero-encourage",
  "zero-explique-droite",
  "zero-explique-gauche",
  "zero-fier",
  "zero-gonfle",
  "zero-joie",
  "zero-joues",
  "zero-mille",
  "zero-neutre",
  "zero-reflexion",
  "zero-salut",
  "zero-surprise",
  "zero-triste"
 ],
 "boutique": [],
 "objets": [],
 "badges": [],
 "habitants": [],
 "persos": [
  "grand-oubli",
  "grignoteur-ami",
  "grignoteur-compte",
  "grignoteur-croque",
  "grignoteur-espiegle",
  "grignoteur-esquive",
  "grignoteur-touche",
  "grignoteur-triste",
  "ixe-amie",
  "ixe-camouflage",
  "ixe-neutre",
  "ixe-rire",
  "ixe-surprise"
 ]
};
