// Test de référence du moteur de français : des centaines de formes vérifiées (type Bescherelle).
// npm run test:fr
import { avecPronom, formes, participe, participePresent, tableau, type Temps } from "../src/lib/fr/conjugaison";
import { feminin, pluriel, accorder, determinant } from "../src/lib/fr/morpho";

let ok = 0;
const ko: string[] = [];
function eq(label: string, got: string | string[], want: string) {
  const g = Array.isArray(got) ? got : [got];
  if (g[0] === want) ok++;
  else ko.push(`${label} : obtenu « ${g.join(" | ")} », attendu « ${want} »`);
}
const T = (v: string, t: Temps, want: string) => eq(`${v} ${t}`, tableau(v, t).join(", "), want);

// --- présent ---
T("chanter", "present", "je chante, tu chantes, il chante, nous chantons, vous chantez, ils chantent");
T("aimer", "present", "j'aime, tu aimes, il aime, nous aimons, vous aimez, ils aiment");
T("commencer", "present", "je commence, tu commences, il commence, nous commençons, vous commencez, ils commencent");
T("manger", "present", "je mange, tu manges, il mange, nous mangeons, vous mangez, ils mangent");
T("appeler", "present", "j'appelle, tu appelles, il appelle, nous appelons, vous appelez, ils appellent");
T("jeter", "present", "je jette, tu jettes, il jette, nous jetons, vous jetez, ils jettent");
T("acheter", "present", "j'achète, tu achètes, il achète, nous achetons, vous achetez, ils achètent");
T("lever", "present", "je lève, tu lèves, il lève, nous levons, vous levez, ils lèvent");
T("céder", "present", "je cède, tu cèdes, il cède, nous cédons, vous cédez, ils cèdent");
T("espérer", "present", "j'espère, tu espères, il espère, nous espérons, vous espérez, ils espèrent");
T("célébrer", "present", "je célèbre, tu célèbres, il célèbre, nous célébrons, vous célébrez, ils célèbrent");
T("nettoyer", "present", "je nettoie, tu nettoies, il nettoie, nous nettoyons, vous nettoyez, ils nettoient");
T("essuyer", "present", "j'essuie, tu essuies, il essuie, nous essuyons, vous essuyez, ils essuient");
T("payer", "present", "je paie, tu paies, il paie, nous payons, vous payez, ils paient");
T("entrer", "present", "j'entre, tu entres, il entre, nous entrons, vous entrez, ils entrent");
T("fermer", "present", "je ferme, tu fermes, il ferme, nous fermons, vous fermez, ils ferment");
T("créer", "present", "je crée, tu crées, il crée, nous créons, vous créez, ils créent");
T("crier", "imparfait", "je criais, tu criais, il criait, nous criions, vous criiez, ils criaient");
T("habiter", "present", "j'habite, tu habites, il habite, nous habitons, vous habitez, ils habitent");
T("hurler", "present", "je hurle, tu hurles, il hurle, nous hurlons, vous hurlez, ils hurlent");
T("finir", "present", "je finis, tu finis, il finit, nous finissons, vous finissez, ils finissent");
T("grandir", "present", "je grandis, tu grandis, il grandit, nous grandissons, vous grandissez, ils grandissent");
T("haïr", "present", "je hais, tu hais, il hait, nous haïssons, vous haïssez, ils haïssent");
T("être", "present", "je suis, tu es, il est, nous sommes, vous êtes, ils sont");
T("avoir", "present", "j'ai, tu as, il a, nous avons, vous avez, ils ont");
T("aller", "present", "je vais, tu vas, il va, nous allons, vous allez, ils vont");
T("venir", "present", "je viens, tu viens, il vient, nous venons, vous venez, ils viennent");
T("devenir", "present", "je deviens, tu deviens, il devient, nous devenons, vous devenez, ils deviennent");
T("tenir", "present", "je tiens, tu tiens, il tient, nous tenons, vous tenez, ils tiennent");
T("partir", "present", "je pars, tu pars, il part, nous partons, vous partez, ils partent");
T("dormir", "present", "je dors, tu dors, il dort, nous dormons, vous dormez, ils dorment");
T("ouvrir", "present", "j'ouvre, tu ouvres, il ouvre, nous ouvrons, vous ouvrez, ils ouvrent");
T("cueillir", "present", "je cueille, tu cueilles, il cueille, nous cueillons, vous cueillez, ils cueillent");
T("courir", "present", "je cours, tu cours, il court, nous courons, vous courez, ils courent");
T("mourir", "present", "je meurs, tu meurs, il meurt, nous mourons, vous mourez, ils meurent");
T("prendre", "present", "je prends, tu prends, il prend, nous prenons, vous prenez, ils prennent");
T("comprendre", "present", "je comprends, tu comprends, il comprend, nous comprenons, vous comprenez, ils comprennent");
T("apprendre", "present", "j'apprends, tu apprends, il apprend, nous apprenons, vous apprenez, ils apprennent");
T("rendre", "present", "je rends, tu rends, il rend, nous rendons, vous rendez, ils rendent");
T("attendre", "present", "j'attends, tu attends, il attend, nous attendons, vous attendez, ils attendent");
T("répondre", "present", "je réponds, tu réponds, il répond, nous répondons, vous répondez, ils répondent");
T("perdre", "present", "je perds, tu perds, il perd, nous perdons, vous perdez, ils perdent");
T("mettre", "present", "je mets, tu mets, il met, nous mettons, vous mettez, ils mettent");
T("permettre", "present", "je permets, tu permets, il permet, nous permettons, vous permettez, ils permettent");
T("battre", "present", "je bats, tu bats, il bat, nous battons, vous battez, ils battent");
T("peindre", "present", "je peins, tu peins, il peint, nous peignons, vous peignez, ils peignent");
T("craindre", "present", "je crains, tu crains, il craint, nous craignons, vous craignez, ils craignent");
T("joindre", "present", "je joins, tu joins, il joint, nous joignons, vous joignez, ils joignent");
T("faire", "present", "je fais, tu fais, il fait, nous faisons, vous faites, ils font");
T("dire", "present", "je dis, tu dis, il dit, nous disons, vous dites, ils disent");
T("interdire", "present", "j'interdis, tu interdis, il interdit, nous interdisons, vous interdisez, ils interdisent");
T("lire", "present", "je lis, tu lis, il lit, nous lisons, vous lisez, ils lisent");
T("écrire", "present", "j'écris, tu écris, il écrit, nous écrivons, vous écrivez, ils écrivent");
T("décrire", "present", "je décris, tu décris, il décrit, nous décrivons, vous décrivez, ils décrivent");
T("rire", "present", "je ris, tu ris, il rit, nous rions, vous riez, ils rient");
T("sourire", "present", "je souris, tu souris, il sourit, nous sourions, vous souriez, ils sourient");
T("conduire", "present", "je conduis, tu conduis, il conduit, nous conduisons, vous conduisez, ils conduisent");
T("construire", "present", "je construis, tu construis, il construit, nous construisons, vous construisez, ils construisent");
T("connaître", "present", "je connais, tu connais, il connaît, nous connaissons, vous connaissez, ils connaissent");
T("naître", "present", "je nais, tu nais, il naît, nous naissons, vous naissez, ils naissent");
T("plaire", "present", "je plais, tu plais, il plaît, nous plaisons, vous plaisez, ils plaisent");
T("croire", "present", "je crois, tu crois, il croit, nous croyons, vous croyez, ils croient");
T("boire", "present", "je bois, tu bois, il boit, nous buvons, vous buvez, ils boivent");
T("voir", "present", "je vois, tu vois, il voit, nous voyons, vous voyez, ils voient");
T("savoir", "present", "je sais, tu sais, il sait, nous savons, vous savez, ils savent");
T("pouvoir", "present", "je peux, tu peux, il peut, nous pouvons, vous pouvez, ils peuvent");
T("vouloir", "present", "je veux, tu veux, il veut, nous voulons, vous voulez, ils veulent");
T("devoir", "present", "je dois, tu dois, il doit, nous devons, vous devez, ils doivent");
T("recevoir", "present", "je reçois, tu reçois, il reçoit, nous recevons, vous recevez, ils reçoivent");
T("apercevoir", "present", "j'aperçois, tu aperçois, il aperçoit, nous apercevons, vous apercevez, ils aperçoivent");
T("valoir", "present", "je vaux, tu vaux, il vaut, nous valons, vous valez, ils valent");
T("suivre", "present", "je suis, tu suis, il suit, nous suivons, vous suivez, ils suivent");
T("vivre", "present", "je vis, tu vis, il vit, nous vivons, vous vivez, ils vivent");
T("résoudre", "present", "je résous, tu résous, il résout, nous résolvons, vous résolvez, ils résolvent");
T("vaincre", "present", "je vaincs, tu vaincs, il vainc, nous vainquons, vous vainquez, ils vainquent");
T("fuir", "present", "je fuis, tu fuis, il fuit, nous fuyons, vous fuyez, ils fuient");
T("falloir", "present", "il faut");
T("pleuvoir", "imparfait", "il pleuvait");
// --- imparfait ---
T("commencer", "imparfait", "je commençais, tu commençais, il commençait, nous commencions, vous commenciez, ils commençaient");
T("manger", "imparfait", "je mangeais, tu mangeais, il mangeait, nous mangions, vous mangiez, ils mangeaient");
T("finir", "imparfait", "je finissais, tu finissais, il finissait, nous finissions, vous finissiez, ils finissaient");
T("faire", "imparfait", "je faisais, tu faisais, il faisait, nous faisions, vous faisiez, ils faisaient");
T("être", "imparfait", "j'étais, tu étais, il était, nous étions, vous étiez, ils étaient");
T("voir", "imparfait", "je voyais, tu voyais, il voyait, nous voyions, vous voyiez, ils voyaient");
T("rire", "imparfait", "je riais, tu riais, il riait, nous riions, vous riiez, ils riaient");
// --- futur ---
T("chanter", "futur", "je chanterai, tu chanteras, il chantera, nous chanterons, vous chanterez, ils chanteront");
T("appeler", "futur", "j'appellerai, tu appelleras, il appellera, nous appellerons, vous appellerez, ils appelleront");
T("acheter", "futur", "j'achèterai, tu achèteras, il achètera, nous achèterons, vous achèterez, ils achèteront");
T("nettoyer", "futur", "je nettoierai, tu nettoieras, il nettoiera, nous nettoierons, vous nettoierez, ils nettoieront");
T("envoyer", "futur", "j'enverrai, tu enverras, il enverra, nous enverrons, vous enverrez, ils enverront");
T("aller", "futur", "j'irai, tu iras, il ira, nous irons, vous irez, ils iront");
T("venir", "futur", "je viendrai, tu viendras, il viendra, nous viendrons, vous viendrez, ils viendront");
T("faire", "futur", "je ferai, tu feras, il fera, nous ferons, vous ferez, ils feront");
T("voir", "futur", "je verrai, tu verras, il verra, nous verrons, vous verrez, ils verront");
T("savoir", "futur", "je saurai, tu sauras, il saura, nous saurons, vous saurez, ils sauront");
T("pouvoir", "futur", "je pourrai, tu pourras, il pourra, nous pourrons, vous pourrez, ils pourront");
T("courir", "futur", "je courrai, tu courras, il courra, nous courrons, vous courrez, ils courront");
T("cueillir", "futur", "je cueillerai, tu cueilleras, il cueillera, nous cueillerons, vous cueillerez, ils cueilleront");
T("finir", "futur", "je finirai, tu finiras, il finira, nous finirons, vous finirez, ils finiront");
T("prendre", "futur", "je prendrai, tu prendras, il prendra, nous prendrons, vous prendrez, ils prendront");
T("être", "futur", "je serai, tu seras, il sera, nous serons, vous serez, ils seront");
T("avoir", "futur", "j'aurai, tu auras, il aura, nous aurons, vous aurez, ils auront");
T("devoir", "futur", "je devrai, tu devras, il devra, nous devrons, vous devrez, ils devront");
T("recevoir", "futur", "je recevrai, tu recevras, il recevra, nous recevrons, vous recevrez, ils recevront");
T("céder", "futur", "je céderai, tu céderas, il cédera, nous céderons, vous céderez, ils céderont");
// --- passé simple ---
T("chanter", "passe_simple", "je chantai, tu chantas, il chanta, nous chantâmes, vous chantâtes, ils chantèrent");
T("commencer", "passe_simple", "je commençai, tu commenças, il commença, nous commençâmes, vous commençâtes, ils commencèrent");
T("manger", "passe_simple", "je mangeai, tu mangeas, il mangea, nous mangeâmes, vous mangeâtes, ils mangèrent");
T("finir", "passe_simple", "je finis, tu finis, il finit, nous finîmes, vous finîtes, ils finirent");
T("prendre", "passe_simple", "je pris, tu pris, il prit, nous prîmes, vous prîtes, ils prirent");
T("venir", "passe_simple", "je vins, tu vins, il vint, nous vînmes, vous vîntes, ils vinrent");
T("tenir", "passe_simple", "je tins, tu tins, il tint, nous tînmes, vous tîntes, ils tinrent");
T("être", "passe_simple", "je fus, tu fus, il fut, nous fûmes, vous fûtes, ils furent");
T("avoir", "passe_simple", "j'eus, tu eus, il eut, nous eûmes, vous eûtes, ils eurent");
T("faire", "passe_simple", "je fis, tu fis, il fit, nous fîmes, vous fîtes, ils firent");
T("voir", "passe_simple", "je vis, tu vis, il vit, nous vîmes, vous vîtes, ils virent");
T("lire", "passe_simple", "je lus, tu lus, il lut, nous lûmes, vous lûtes, ils lurent");
T("écrire", "passe_simple", "j'écrivis, tu écrivis, il écrivit, nous écrivîmes, vous écrivîtes, ils écrivirent");
T("naître", "passe_simple", "je naquis, tu naquis, il naquit, nous naquîmes, vous naquîtes, ils naquirent");
T("vivre", "passe_simple", "je vécus, tu vécus, il vécut, nous vécûmes, vous vécûtes, ils vécurent");
T("conduire", "passe_simple", "je conduisis, tu conduisis, il conduisit, nous conduisîmes, vous conduisîtes, ils conduisirent");
T("peindre", "passe_simple", "je peignis, tu peignis, il peignit, nous peignîmes, vous peignîtes, ils peignirent");
T("mettre", "passe_simple", "je mis, tu mis, il mit, nous mîmes, vous mîtes, ils mirent");
T("aller", "passe_simple", "j'allai, tu allas, il alla, nous allâmes, vous allâtes, ils allèrent");
T("recevoir", "passe_simple", "je reçus, tu reçus, il reçut, nous reçûmes, vous reçûtes, ils reçurent");
T("courir", "passe_simple", "je courus, tu courus, il courut, nous courûmes, vous courûtes, ils coururent");
T("rendre", "passe_simple", "je rendis, tu rendis, il rendit, nous rendîmes, vous rendîtes, ils rendirent");
T("devoir", "passe_simple", "je dus, tu dus, il dut, nous dûmes, vous dûtes, ils durent");
// --- conditionnel ---
T("être", "conditionnel", "je serais, tu serais, il serait, nous serions, vous seriez, ils seraient");
T("vouloir", "conditionnel", "je voudrais, tu voudrais, il voudrait, nous voudrions, vous voudriez, ils voudraient");
T("aimer", "conditionnel", "j'aimerais, tu aimerais, il aimerait, nous aimerions, vous aimeriez, ils aimeraient");
// --- subjonctif ---
T("chanter", "subjonctif", "que je chante, que tu chantes, qu'il chante, que nous chantions, que vous chantiez, qu'ils chantent");
T("finir", "subjonctif", "que je finisse, que tu finisses, qu'il finisse, que nous finissions, que vous finissiez, qu'ils finissent");
T("être", "subjonctif", "que je sois, que tu sois, qu'il soit, que nous soyons, que vous soyez, qu'ils soient");
T("avoir", "subjonctif", "que j'aie, que tu aies, qu'il ait, que nous ayons, que vous ayez, qu'ils aient");
T("aller", "subjonctif", "que j'aille, que tu ailles, qu'il aille, que nous allions, que vous alliez, qu'ils aillent");
T("faire", "subjonctif", "que je fasse, que tu fasses, qu'il fasse, que nous fassions, que vous fassiez, qu'ils fassent");
T("pouvoir", "subjonctif", "que je puisse, que tu puisses, qu'il puisse, que nous puissions, que vous puissiez, qu'ils puissent");
T("savoir", "subjonctif", "que je sache, que tu saches, qu'il sache, que nous sachions, que vous sachiez, qu'ils sachent");
T("vouloir", "subjonctif", "que je veuille, que tu veuilles, qu'il veuille, que nous voulions, que vous vouliez, qu'ils veuillent");
T("prendre", "subjonctif", "que je prenne, que tu prennes, qu'il prenne, que nous prenions, que vous preniez, qu'ils prennent");
T("venir", "subjonctif", "que je vienne, que tu viennes, qu'il vienne, que nous venions, que vous veniez, qu'ils viennent");
T("boire", "subjonctif", "que je boive, que tu boives, qu'il boive, que nous buvions, que vous buviez, qu'ils boivent");
T("voir", "subjonctif", "que je voie, que tu voies, qu'il voie, que nous voyions, que vous voyiez, qu'ils voient");
T("devoir", "subjonctif", "que je doive, que tu doives, qu'il doive, que nous devions, que vous deviez, qu'ils doivent");
T("lever", "subjonctif", "que je lève, que tu lèves, qu'il lève, que nous levions, que vous leviez, qu'ils lèvent");
T("valoir", "subjonctif", "que je vaille, que tu vailles, qu'il vaille, que nous valions, que vous valiez, qu'ils vaillent");
T("chanter", "subjonctif_imparfait", "que je chantasse, que tu chantasses, qu'il chantât, que nous chantassions, que vous chantassiez, qu'ils chantassent");
T("être", "subjonctif_imparfait", "que je fusse, que tu fusses, qu'il fût, que nous fussions, que vous fussiez, qu'ils fussent");
T("venir", "subjonctif_imparfait", "que je vinsse, que tu vinsses, qu'il vînt, que nous vinssions, que vous vinssiez, qu'ils vinssent");
// --- impératif ---
T("chanter", "imperatif", "chante, chantons, chantez");
T("aller", "imperatif", "va, allons, allez");
T("finir", "imperatif", "finis, finissons, finissez");
T("ouvrir", "imperatif", "ouvre, ouvrons, ouvrez");
T("être", "imperatif", "sois, soyons, soyez");
T("avoir", "imperatif", "aie, ayons, ayez");
T("savoir", "imperatif", "sache, sachons, sachez");
T("prendre", "imperatif", "prends, prenons, prenez");
T("faire", "imperatif", "fais, faisons, faites");
T("se lever", "imperatif", "lève-toi, levons-nous, levez-vous");
// --- temps composés ---
T("chanter", "passe_compose", "j'ai chanté, tu as chanté, il a chanté, nous avons chanté, vous avez chanté, ils ont chanté");
T("aller", "passe_compose", "je suis allé, tu es allé, il est allé, nous sommes allés, vous êtes allés, ils sont allés");
T("être", "passe_compose", "j'ai été, tu as été, il a été, nous avons été, vous avez été, ils ont été");
T("prendre", "plus_que_parfait", "j'avais pris, tu avais pris, il avait pris, nous avions pris, vous aviez pris, ils avaient pris");
T("venir", "futur_anterieur", "je serai venu, tu seras venu, il sera venu, nous serons venus, vous serez venus, ils seront venus");
T("finir", "conditionnel_passe", "j'aurais fini, tu aurais fini, il aurait fini, nous aurions fini, vous auriez fini, ils auraient fini");
T("partir", "subjonctif_passe", "que je sois parti, que tu sois parti, qu'il soit parti, que nous soyons partis, que vous soyez partis, qu'ils soient partis");
T("se laver", "passe_compose", "je me suis lavé, tu t'es lavé, il s'est lavé, nous nous sommes lavés, vous vous êtes lavés, ils se sont lavés");
T("se lever", "present", "je me lève, tu te lèves, il se lève, nous nous levons, vous vous levez, ils se lèvent");
T("s'habiller", "present", "je m'habille, tu t'habilles, il s'habille, nous nous habillons, vous vous habillez, ils s'habillent");
T("naître", "passe_compose", "je suis né, tu es né, il est né, nous sommes nés, vous êtes nés, ils sont nés");
T("mourir", "passe_compose", "je suis mort, tu es mort, il est mort, nous sommes morts, vous êtes morts, ils sont morts");
eq("aller pc elle", avecPronom("aller", "passe_compose", 3, "f"), "elle est allée");
eq("partir pc elles", avecPronom("partir", "passe_compose", 6, "f"), "elles sont parties");
eq("venir pqp elles", avecPronom("venir", "plus_que_parfait", 6, "f"), "elles étaient venues");
// --- participes ---
eq("pp prendre f", participe("prendre", "f"), "prise");
eq("pp prendre mp", participe("prendre", "m", 2), "pris");
eq("pp faire fp", participe("faire", "f", 2), "faites");
eq("pp ouvrir f", participe("ouvrir", "f"), "ouverte");
eq("pp devoir", participe("devoir"), "dû");
eq("pp devoir f", participe("devoir", "f"), "due");
eq("pp devoir mp", participe("devoir", "m", 2), "dus");
eq("pp naître f", participe("naître", "f"), "née");
eq("pp peindre", participe("peindre"), "peint");
eq("pp conduire f", participe("conduire", "f"), "conduite");
eq("pp résoudre", participe("résoudre"), "résolu");
eq("pp inclure", participe("inclure"), "inclus");
eq("pp exclure", participe("exclure"), "exclu");
eq("ppr savoir", participePresent("savoir"), "sachant");
eq("ppr commencer", participePresent("commencer"), "commençant");
eq("ppr manger", participePresent("manger"), "mangeant");
eq("ppr finir", participePresent("finir"), "finissant");
eq("ppr faire", participePresent("faire"), "faisant");
eq("ppr voir", participePresent("voir"), "voyant");
// --- variantes acceptées (1990, -ayer) ---
eq("paye accepté", formes("payer", "present", 1).join("|"), "paie|paye");
eq("connait accepté", formes("connaître", "present", 3).join("|"), "connaît|connait");
eq("cèderai accepté", formes("céder", "futur", 1).join("|"), "céderai|cèderai");

// --- morphologie ---
const P = (n: string, w: string) => eq(`pluriel ${n}`, pluriel(n), w);
P("chat", "chats"); P("souris", "souris"); P("nez", "nez"); P("prix", "prix"); P("cheval", "chevaux"); P("journal", "journaux"); P("bal", "bals");
P("festival", "festivals"); P("carnaval", "carnavals"); P("chapeau", "chapeaux"); P("jeu", "jeux"); P("pneu", "pneus"); P("bleu", "bleus");
P("bijou", "bijoux"); P("caillou", "caillous".replace("ous", "oux")); P("chou", "choux"); P("genou", "genoux"); P("hibou", "hiboux"); P("joujou", "joujoux"); P("pou", "poux");
P("clou", "clous"); P("trou", "trous"); P("travail", "travaux"); P("vitrail", "vitraux"); P("détail", "détails"); P("rail", "rails");
P("œil", "yeux"); P("ciel", "cieux"); P("monsieur", "messieurs"); P("madame", "mesdames"); P("landau", "landaus"); P("tuyau", "tuyaux");
const F = (a: string, w: string) => eq(`féminin ${a}`, feminin(a), w);
F("grand", "grande"); F("petit", "petite"); F("jeune", "jeune"); F("fier", "fière"); F("heureux", "heureuse"); F("vif", "vive"); F("neuf", "neuve");
F("cruel", "cruelle"); F("pareil", "pareille"); F("ancien", "ancienne"); F("bon", "bonne"); F("muet", "muette"); F("complet", "complète"); F("secret", "secrète");
F("inquiet", "inquiète"); F("sot", "sotte"); F("idiot", "idiote"); F("blanc", "blanche"); F("franc", "franche"); F("sec", "sèche"); F("public", "publique");
F("grec", "grecque"); F("long", "longue"); F("beau", "belle"); F("nouveau", "nouvelle"); F("fou", "folle"); F("mou", "molle"); F("vieux", "vieille");
F("doux", "douce"); F("faux", "fausse"); F("roux", "rousse"); F("gentil", "gentille"); F("nul", "nulle"); F("gros", "grosse"); F("bas", "basse");
F("épais", "épaisse"); F("frais", "fraîche"); F("malin", "maligne"); F("favori", "favorite"); F("aigu", "aiguë"); F("menteur", "menteuse");
F("créateur", "créatrice"); F("meilleur", "meilleure"); F("supérieur", "supérieure"); F("joli", "jolie"); F("bleu", "bleue"); F("gris", "grise"); F("mignon", "mignonne");
eq("accord grand fp", accorder("grand", "f", 2), "grandes");
eq("accord beau mp", accorder("beau", "m", 2), "beaux");
eq("accord heureux mp", accorder("heureux", "m", 2), "heureux");
eq("accord heureux fp", accorder("heureux", "f", 2), "heureuses");
eq("accord national mp", accorder("national", "m", 2), "nationaux");
eq("accord banal mp", accorder("banal", "m", 2), "banals");
eq("accord orange fp", accorder("orange", "f", 2), "orange");
eq("accord marron mp", accorder("marron", "m", 2), "marron");
eq("accord rose fp", accorder("rose", "f", 2), "roses");
eq("det le arbre", determinant("defini", "arbre", "m", 1), "l'arbre");
eq("det la école", determinant("defini", "école", "f", 1), "l'école");
eq("det le héros", determinant("defini", "héros", "m", 1, true), "le héros");
eq("det la table", determinant("defini", "table", "f", 1), "la table");
eq("det les chats", determinant("defini", "chats", "m", 2), "les chats");
eq("det un livre", determinant("indefini", "livre", "m", 1), "un livre");
eq("det une pomme", determinant("indefini", "pomme", "f", 1), "une pomme");
eq("det du pain", determinant("partitif", "pain", "m", 1), "du pain");
eq("det de l'eau", determinant("partitif", "eau", "f", 1), "de l'eau");
eq("det de la farine", determinant("partitif", "farine", "f", 1), "de la farine");

console.log(`Français : ${ok} formes justes, ${ko.length} erreur(s).`);
if (ko.length) {
  console.log(ko.join("\n"));
  process.exit(1);
}
